default: &default
  adapter: postgresql
  pool: 5
  username: 'root'
  password: 'root'
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: blog_development
production:
  <<: *default
  database: blog_production